language:  node_js 
node_js:
  - node
apt:
  packages:
  - build-essential
  - libcairo2-dev 
  - libpango1.0-dev
  - libjpeg-dev 
  - libgif-dev 
  - librsvg2-dev

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g gulp-cli
  - npm install
